groupName: acme.cluster.local

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: metallapan/cert-manager-linode
  tag: 0.3.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
